name: 部署文档

on:
  # push:
  #   branches:
  #     - main # default branch
  schedule:
   # * is a special character in YAML so you have to quote this string
    - cron: '* 0,6,12,18 * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - run: pnpm i
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build

      - run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./dist
